# -*- coding: utf-8 -*-
"""ketha_anudeep_kumar_reddy_Presidency_university.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i6A0xT6S0yLjZYXLFPrgFL8eqrfmlmOm

**KETHA ANUDEEP KUMAR REDDY**

**PRESIDENCY UNIVERSITY**
"""

#importing libraries
import csv
import re
import time
import psutil

# Read the input files
with open('find_words.txt', 'r') as f:
    find_words = set(word.strip() for word in f.readlines())

with open('french_dictionary.csv', 'r') as f:
    reader = csv.reader(f)
    french_dict = {rows[0]:rows[1] for rows in reader}

with open('t8.shakespeare.txt', 'r') as f:
    text = f.read()

# Replace words and count frequency
replaced_words = {}
for word in find_words:
    if word in french_dict:
        pattern = r'\b{}\b'.format(word)
        count = len(re.findall(pattern, text))
        text = re.sub(pattern, french_dict[word], text)
        replaced_words[word] = [french_dict[word], count]

# Write the output files
with open('frequency.csv', 'w') as f:
    writer = csv.writer(f)
    writer.writerow(['English word', 'French word', 'Frequency'])
    for word, info in replaced_words.items():
        writer.writerow([word, info[0], info[1]])

with open('t8.shakespeare.translated.txt', 'w') as f:
    f.write(text)

# Write the performance file
memory_usage = psutil.Process().memory_info().rss / 1024 / 1024
with open('performance.txt', 'w') as f:
    f.write('Time to process: {} minutes {} seconds\n'.format(*divmod(time.process_time(), 60)))
    f.write('Memory used: {:.2f} MB'.format(memory_usage))